### ISSUE TITLE
Completar con queries en los resolver las funciones necesarias para el front-end

### ISSUE THREAD

**Issue by JoseMari98** [votUCA/votUCAback#48]
Listar las votaciones pendientes que tiene un usuario en concreto. Tabla proceso electoral, listar varchar:nombre.

Listar los candidatos (string:candidato) en funcion de una eleccion dada.

Listar los candidatos con el porcentaje de votos.

Listar los censos: secretario (tabla proceso electoral), subsecretario, votantes(tabla censo)

**Comment by IvanCastilloCaro** [comment]
Listar los candidatos (string:candidato) en funcion de una eleccion dada -> Este Query está hecho por defecto, ya que al devolver los datos de la elección a partir de un ID (findByID), se puede seleccionar únicamente el candidato en GraphQL, por lo que no tiene sentido añadir un nuevo Query
